### ISSUE TITLE
Not all scenes are listed when calling the `utils/scene` endpoint

### ISSUE THREAD

**Issue by grrizzly** [gwaredd/unium#1]
Hi there,

First of all I want to say thank you for putting together this library. It is pretty well thought out and, for an initial, "experimental" version, it has been surprisingly stable!

I am in the process of writing a Javascript client wrapper for the HTTP API and ran into what appears to be either a documentation issue or a bug. When making a GET request to `utils/scene/oijsfiojeoijioejfjoi` while running the tutorial scene, I get the following response:

```json
{"loading":"ojieiofjeoijfe"}
```

Indeed, when looking at the logs, I see the following:

![image](https://user-images.githubusercontent.com/1242640/29725211-309849dc-8980-11e7-9ace-88053fb7ea5c.png)

However, the PDF states that the endpoint should "Load a scene by name (e.g. /utils/scene/tutorial). If no name given then list all scenes."

Rather than fixing it directly, I think it would be great if the functionality was split into multiple endpoints, following a more RESTful model:
   - GET `utils/scenes` - lists the available scenes in a JSON array
   - GET `utils/scenes/<name>` loads metadata about a scene. Returns a 404 if the scene does not exist
   - POST `utils/scenes/<name>` loads the scene by name. Returns a 400 (bad request) if the scene is not available to load.
 
Doing this split would separate functionality into explicit read/write calls and simplify the design of a client library. By leveraging HTTP semantics, it also would make the API more familiar to those with a web development background.

How does this sound to you? Do you have other ideas on how you'd like to see this work? I am happy to consume it whatever you decide. Thanks again!

**Comment by gwaredd** [comment]
Thanks :) It is the culmination of several things coming together from various previous projects.

The scene loading could indeed do with some work. It should return a 404 if the scene fails to load or doesn't exist. This would be a bug! Laziness on my part for using SceneManager.LoadScene rather than LoadSceneAsync.

Regarding using HTTP methods to make the interface more web-like, typically I tend to use it when developing. So just being able to open a browser and fire off a URL is very convenient. This is why (almost) everything is a GET request. Of course I could use curl but the ubiquity of the browser is very alluring - for example, I've used my phone in a meeting to debug a problem in a build on another phone off-the-cuff, no development environment or dependencies required.

I will fix the scene loading bug. I want to refactor the way it handles asynchronous operations so this is a good use case for that. Although life commitments means it maybe a couple of weeks before I get a chance to look at it.

Of course, if you prefer, you can add your own custom extensions. It easy to add additional handlers, for example

            RoutesHTTP.Add( "/myutils/scene", HandlerUtils.MyHandlerScene );

**Comment by gwaredd** [comment]
Also, regarding the "not all scenes being listed" - unfortunately this is a unity thing. 

http://answers.unity3d.com/questions/33263/how-to-get-names-of-all-available-levels.html

**Comment by gwaredd** [comment]
I've changed the scene loading so it returns 404 or 200 accordingly.

Also, changed the code that lists the scene so if running in the editor it uses the EditorBuildSettings to get a list of the scenes added to the build list. At runtime it still uses the SceneManager to list loaded scenes (which is less than ideal).

AFAICS there's no clean way to get a list of scenes at runtime without saving them to an external file when you build. This would be easy to add but doesn't feel like a "library" feature to me.

Open to ideas though

G
