### ISSUE TITLE
Running unium for a built project

### ISSUE THREAD

**Issue by pustynnik** [gwaredd/unium#3]
Hi,

Sorry if my question may sound silly or naive, I am a total novice in Unity.
I am able to interact with the app through http://localhost:8342 when I run it from Unity editor. However, if build the app and run the .exe file instead, I cannot access the unium web server. 
Is there a way to enable the web server in the built apps?

/Sergey

**Comment by gwaredd** [comment]
Hey.

It's not a silly question, it's just something not obvious :) The quick answer is make sure you check the **development build** checkbox when you create the exe.

TL;DR

By default, Unium is compiled out for release builds. This is because it was always intended as a development library and it was a way to help prevent debug being accidentally put into a release version of the app. This is configurable though, you can either:

- check the "development build" flag
- or ... add UNIUM_ENABLE as a compile symbol in the player settings

I should probably update the documentation to make it more obvious :)

HTH

Gw

**Comment by pustynnik** [comment]
Thank you!
The "development build" flag made it work. However, I was not able to access unium via localhost, but could do it via local IP address.
/Sergey

**Comment by gwaredd** [comment]
Glad you got it working :)

I'll take a look at the code, you should be able to access it on both interfaces but I may have done something daft ;)
