### ISSUE TITLE
how can i command touch event?

### ISSUE THREAD

**Issue by YunJongDeuk** [gwaredd/unium#4]
Does unium support touch events?

**Comment by gwaredd** [comment]
Unium itself does not emulate input events, unfortunately that would be outside the scope of the library.

However, you can still use it to automate input. For example, to click a standard Unity UI button, you can directly invoke the onClick() event on the underlying component, e.g.

     /q/scene/Canvas/Button.Button.onClick.Invoke()

You would need to provide some kind of interface to call for other types of input but that depends on the architecture of your game. For example, lets say you have a puzzle game and the player clicks on tiles to select them (which results in a raycast into the scene from the screen position). Then my approach would either be to directly invoke the "selected" event on the underlying tile (bypassing the input entirely as per button example above), or to add a "click here" function on the code that uses the values passed in (rather than reading them from the input). Alternatively, you can replace the standard unity Input with a "broker" object making it easier to override input at a more global level - although this may require some re-architecturing of your game.

Unium merely provides a way to remotely retrieve state, call code or change values. How you use it for is up to you :)

Hope that helps

**Comment by gwaredd** [comment]
**Update**: I've added a new component UniumSimulate, that uses the Unity EventSystem to emulate UI events. This doesn't do everything but may help with some UI test cases.

See documentation for details, but it lets you do this ...

```
/q/simulate.click(20,600)
​/q/simulate.drag(0,0,100,100,0.5)
```

**Comment by nccho** [comment]
I apply UniumSimulate. but An error has occurred.
What is the correct method of use?

![unium simulate](https://user-images.githubusercontent.com/2323255/43113924-631108f0-8f37-11e8-9ae8-a45e352f6eb3.png)
![error log](https://user-images.githubusercontent.com/2323255/43113926-65559e1e-8f37-11e8-8830-c658a7b48596.png)

**Comment by gwaredd** [comment]
Simulate uses the EventSystem to invoke pointer clicker events. It's possible if there isn't an event system in the scene it's throwing an exception. However, I've tested that scenario and it works ok for me. It's also possible the exception is being thrown in the underlying code being tested.

Have you tried stepping through the click handler in a debugger?

**Comment by nccho** [comment]
@gwaredd 
I will try as you say.
Thank you for your reply.
