### ISSUE TITLE
HandlerFile.DownloadFile not working on Android and iOS devices

### ISSUE THREAD

**Issue by yuewah** [gwaredd/unium#7]
use new WWW( "file:///" + filepath ) instead of new WWW( filepath )  will fix the problem.

**Comment by gwaredd** [comment]
Hey,

I've had a quick look at this and loading out of both streaming assets and persistent storage works OK for me.

Internally "drives" are "mounted" to get their path, so the file:/// bit comes from the [streaming assets path](https://github.com/gwaredd/unium/blob/master/Assets/Unium/UniumComponent.cs#L73) when it is added to the list.

For example, the path `/file/streaming/favicon.ico` resolves as `jar:file:///data/app/com.gwaredd.unium.tutorial-2/base.apk!/assets/favicon.ico` for me on device.

This is something I changed recently, are you using the latest code? Also, is this trying to get files from streaming assets folder?

Thanks

Gw

**Comment by yuewah** [comment]
I am trying to get files from persistent storage using WWW.
btw, my project android settings for write permission is Internal instead of External (SD Card)

**Comment by gwaredd** [comment]
Well if adding file:/// works for you I'd be inclined to leave it as is :)

I think you're using an older version as the `HandlerFile.DownloadFile` function was replaced in the [latest code](https://github.com/gwaredd/unium/blob/master/Assets/Unium/Routing/HandlerFile.cs#L172) in favour of switching between native file handling or WWW at run time. So on android, System.IO is used for persistent storage and WWW for streaming assets, which fixes the android issues.

Unfortunately I haven't been able to test it on iOS as my certificate has expired but the documentation seems to suggest this should work.

Thanks for reporting this bug but I believe it's fixed in the latest version (on github at least) - unless you tell me otherwise.
