### ISSUE TITLE
Websockets in Unity 2019 and 2020

### ISSUE THREAD

**Issue by tacman** [gwaredd/unium#87]
I'm running the tutorial, and the RESTful interface works fine, but the steps that use websockets fail with the message

Error connecting to game - is it running?
Connection closed

Debugging the JS, I see

Firefox can’t establish a connection to the server at ws://localhost:8342/ws. tutorial.js:34:48624

This isn't surprising, since UNet is deprecated and Unity is changing their networking libraries.  Is there a Websockets library that needs to be installed or enabled for this to work with newer versions of Unity?

And finally, this package is really cool.  Thanks for creating and sharing it.

**Comment by gwaredd** [comment]
WebSockets work fine for me in 2020.1.7. Do you get the same error with chrome?

Unium is largely vanilla C# and works directly with raw sockets rather than use any Unity networking code. Therefore it should be reasonably robust in the face of engine changes. There is no special sauce, any standard websocket library should work.

If you breakpoint [where the connection is accepted](https://github.com/gwaredd/unium/blob/9342d0b4864c08ebaa93ae6f391bc9e58f50a7fb/Assets/Unium/Core/gw.proto.http/Server.cs#L178), does it get as far as establishing the connection?

You could try running the [watch_fps script](https://github.com/gwaredd/unium/blob/master/Dev/scripts/watch_fps.coffee), which is about as simple as they get (you'll need node.js and possibly coffeescript)

Also thanks, it kept me amused :)

**Comment by tacman** [comment]
In the process of trying to do that, I began to wonder if I'm using the
wrong version.  I downloaded the package from the Asset Store, which was
last released in 2018.

Then I tried to download it via adding the github url, but it complained of
no package.json.  But I see there is a upm branch, which does have the
manifest in package.json, version 1.05. which is LOWER than the version in
the asset store (1.1).

So I figured before going forward, I should make sure I'm running the
latest and greatest.  Any chance you could merge upm into master, so it can
be at least pulled from github?  I'm making a fork now and can submit a PR
if I get it to work.  I'd also like to get rid of the deprecation warning
about the WWW package.  Alas, I'm fairly new to Unity, but I should be able
to handle that one.

Tac

**Comment by tacman** [comment]
Ah, I see now, I need to add this to manifest.json


 "com.gwaredd.unium": "https://github.com/gwaredd/unium.git#upm",

**Comment by tacman** [comment]
The tutorial is working now in 2019.4, so I'm guessing the issue was
related to the older code in the Asset Store.

Tac

**Comment by tacman** [comment]
This is such a great tool, kudos to you for putting it together.  It's working for me now, so I'll close this issue.

**Comment by gwaredd** [comment]
You mean [here](https://github.com/gwaredd/unium/blob/master/Assets/Unium/Routing/HandlerFile.cs#L115)?

Is wrong code block being compiled in?

**Comment by tacman** [comment]
Ah, I see that you've already done it.  I'll double-check where I saw it, must have been something else.
